name: First flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
      - uses: actions/checkout@v3
        run: >
          echo "Hello madefpaker!"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: bye world
        run: >
          echo "Bye madefpaker!"
        shell: bash
